// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order-service/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice      float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DeliveryAddress *DeliveryAddress       `protobuf:"bytes,7,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_service_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetDeliveryAddress() *DeliveryAddress {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *Order) GetDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTime
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_service_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type DeliveryAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAddress) Reset() {
	*x = DeliveryAddress{}
	mi := &file_order_service_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAddress) ProtoMessage() {}

func (x *DeliveryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAddress.ProtoReflect.Descriptor instead.
func (*DeliveryAddress) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryAddress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveryAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *DeliveryAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DeliveryAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeliveryAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *DeliveryAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	DeliveryAddress *DeliveryAddress       `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetDeliveryAddress() *DeliveryAddress {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *CreateOrderRequest) GetDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTime
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *DeleteAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesRequest) Reset() {
	*x = ListAddressesRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesRequest) ProtoMessage() {}

func (x *ListAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesRequest.ProtoReflect.Descriptor instead.
func (*ListAddressesRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListAddressesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*DeliveryAddress     `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressesResponse) Reset() {
	*x = ListAddressesResponse{}
	mi := &file_order_service_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressesResponse) ProtoMessage() {}

func (x *ListAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListAddressesResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListAddressesResponse) GetAddresses() []*DeliveryAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type SetDeliveryTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DeliveryTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeliveryTimeRequest) Reset() {
	*x = SetDeliveryTimeRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeliveryTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeliveryTimeRequest) ProtoMessage() {}

func (x *SetDeliveryTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeliveryTimeRequest.ProtoReflect.Descriptor instead.
func (*SetDeliveryTimeRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{9}
}

func (x *SetDeliveryTimeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SetDeliveryTimeRequest) GetDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTime
	}
	return nil
}

type DeliverySlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostalCode    string                 `protobuf:"bytes,1,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverySlotsRequest) Reset() {
	*x = DeliverySlotsRequest{}
	mi := &file_order_service_proto_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverySlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverySlotsRequest) ProtoMessage() {}

func (x *DeliverySlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverySlotsRequest.ProtoReflect.Descriptor instead.
func (*DeliverySlotsRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{10}
}

func (x *DeliverySlotsRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *DeliverySlotsRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type DeliverySlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverySlot) Reset() {
	*x = DeliverySlot{}
	mi := &file_order_service_proto_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverySlot) ProtoMessage() {}

func (x *DeliverySlot) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverySlot.ProtoReflect.Descriptor instead.
func (*DeliverySlot) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{11}
}

func (x *DeliverySlot) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DeliverySlot) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *DeliverySlot) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type DeliverySlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*DeliverySlot        `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverySlotsResponse) Reset() {
	*x = DeliverySlotsResponse{}
	mi := &file_order_service_proto_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverySlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverySlotsResponse) ProtoMessage() {}

func (x *DeliverySlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverySlotsResponse.ProtoReflect.Descriptor instead.
func (*DeliverySlotsResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_order_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverySlotsResponse) GetSlots() []*DeliverySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_order_service_proto_order_proto protoreflect.FileDescriptor

const file_order_service_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x1forder-service/proto/order.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa7\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.order.OrderItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12A\n" +
	"\x10delivery_address\x18\a \x01(\v2\x16.order.DeliveryAddressR\x0fdeliveryAddress\x12?\n" +
	"\rdelivery_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryTime\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\"\xb7\x01\n" +
	"\x0fDeliveryAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\"\xc0\x01\n" +
	"\x12CreateOrderRequest\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.order.OrderItemR\x05items\x12A\n" +
	"\x10delivery_address\x18\x02 \x01(\v2\x16.order.DeliveryAddressR\x0fdeliveryAddress\x12?\n" +
	"\rdelivery_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryTime\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"M\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x14DeleteAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x14ListAddressesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x15ListAddressesResponse\x124\n" +
	"\taddresses\x18\x01 \x03(\v2\x16.order.DeliveryAddressR\taddresses\"t\n" +
	"\x16SetDeliveryTimeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\rdelivery_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryTime\"g\n" +
	"\x14DeliverySlotsRequest\x12\x1f\n" +
	"\vpostal_code\x18\x01 \x01(\tR\n" +
	"postalCode\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x9e\x01\n" +
	"\fDeliverySlot\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\"B\n" +
	"\x15DeliverySlotsResponse\x12)\n" +
	"\x05slots\x18\x01 \x03(\v2\x13.order.DeliverySlotR\x05slots2\x85\x05\n" +
	"\fOrderService\x126\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\f.order.Order\x120\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\f.order.Order\x12B\n" +
	"\x11UpdateOrderStatus\x12\x1f.order.UpdateOrderStatusRequest\x1a\f.order.Order\x12D\n" +
	"\x12AddDeliveryAddress\x12\x16.order.DeliveryAddress\x1a\x16.order.DeliveryAddress\x12G\n" +
	"\x15UpdateDeliveryAddress\x12\x16.order.DeliveryAddress\x1a\x16.order.DeliveryAddress\x12L\n" +
	"\x15DeleteDeliveryAddress\x12\x1b.order.DeleteAddressRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x15ListDeliveryAddresses\x12\x1b.order.ListAddressesRequest\x1a\x1c.order.ListAddressesResponse\x12>\n" +
	"\x0fSetDeliveryTime\x12\x1d.order.SetDeliveryTimeRequest\x1a\f.order.Order\x12V\n" +
	"\x19GetAvailableDeliverySlots\x12\x1b.order.DeliverySlotsRequest\x1a\x1c.order.DeliverySlotsResponseB'Z%github.com/hsibAD/order-service/protob\x06proto3"

var (
	file_order_service_proto_order_proto_rawDescOnce sync.Once
	file_order_service_proto_order_proto_rawDescData []byte
)

func file_order_service_proto_order_proto_rawDescGZIP() []byte {
	file_order_service_proto_order_proto_rawDescOnce.Do(func() {
		file_order_service_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_proto_order_proto_rawDesc), len(file_order_service_proto_order_proto_rawDesc)))
	})
	return file_order_service_proto_order_proto_rawDescData
}

var file_order_service_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_order_service_proto_order_proto_goTypes = []any{
	(*Order)(nil),                    // 0: order.Order
	(*OrderItem)(nil),                // 1: order.OrderItem
	(*DeliveryAddress)(nil),          // 2: order.DeliveryAddress
	(*CreateOrderRequest)(nil),       // 3: order.CreateOrderRequest
	(*GetOrderRequest)(nil),          // 4: order.GetOrderRequest
	(*UpdateOrderStatusRequest)(nil), // 5: order.UpdateOrderStatusRequest
	(*DeleteAddressRequest)(nil),     // 6: order.DeleteAddressRequest
	(*ListAddressesRequest)(nil),     // 7: order.ListAddressesRequest
	(*ListAddressesResponse)(nil),    // 8: order.ListAddressesResponse
	(*SetDeliveryTimeRequest)(nil),   // 9: order.SetDeliveryTimeRequest
	(*DeliverySlotsRequest)(nil),     // 10: order.DeliverySlotsRequest
	(*DeliverySlot)(nil),             // 11: order.DeliverySlot
	(*DeliverySlotsResponse)(nil),    // 12: order.DeliverySlotsResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_order_service_proto_order_proto_depIdxs = []int32{
	1,  // 0: order.Order.items:type_name -> order.OrderItem
	2,  // 1: order.Order.delivery_address:type_name -> order.DeliveryAddress
	13, // 2: order.Order.delivery_time:type_name -> google.protobuf.Timestamp
	13, // 3: order.Order.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: order.Order.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: order.CreateOrderRequest.items:type_name -> order.OrderItem
	2,  // 6: order.CreateOrderRequest.delivery_address:type_name -> order.DeliveryAddress
	13, // 7: order.CreateOrderRequest.delivery_time:type_name -> google.protobuf.Timestamp
	2,  // 8: order.ListAddressesResponse.addresses:type_name -> order.DeliveryAddress
	13, // 9: order.SetDeliveryTimeRequest.delivery_time:type_name -> google.protobuf.Timestamp
	13, // 10: order.DeliverySlotsRequest.date:type_name -> google.protobuf.Timestamp
	13, // 11: order.DeliverySlot.start_time:type_name -> google.protobuf.Timestamp
	13, // 12: order.DeliverySlot.end_time:type_name -> google.protobuf.Timestamp
	11, // 13: order.DeliverySlotsResponse.slots:type_name -> order.DeliverySlot
	3,  // 14: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	4,  // 15: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	5,  // 16: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateOrderStatusRequest
	2,  // 17: order.OrderService.AddDeliveryAddress:input_type -> order.DeliveryAddress
	2,  // 18: order.OrderService.UpdateDeliveryAddress:input_type -> order.DeliveryAddress
	6,  // 19: order.OrderService.DeleteDeliveryAddress:input_type -> order.DeleteAddressRequest
	7,  // 20: order.OrderService.ListDeliveryAddresses:input_type -> order.ListAddressesRequest
	9,  // 21: order.OrderService.SetDeliveryTime:input_type -> order.SetDeliveryTimeRequest
	10, // 22: order.OrderService.GetAvailableDeliverySlots:input_type -> order.DeliverySlotsRequest
	0,  // 23: order.OrderService.CreateOrder:output_type -> order.Order
	0,  // 24: order.OrderService.GetOrder:output_type -> order.Order
	0,  // 25: order.OrderService.UpdateOrderStatus:output_type -> order.Order
	2,  // 26: order.OrderService.AddDeliveryAddress:output_type -> order.DeliveryAddress
	2,  // 27: order.OrderService.UpdateDeliveryAddress:output_type -> order.DeliveryAddress
	14, // 28: order.OrderService.DeleteDeliveryAddress:output_type -> google.protobuf.Empty
	8,  // 29: order.OrderService.ListDeliveryAddresses:output_type -> order.ListAddressesResponse
	0,  // 30: order.OrderService.SetDeliveryTime:output_type -> order.Order
	12, // 31: order.OrderService.GetAvailableDeliverySlots:output_type -> order.DeliverySlotsResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_order_service_proto_order_proto_init() }
func file_order_service_proto_order_proto_init() {
	if File_order_service_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_order_proto_rawDesc), len(file_order_service_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_order_proto_goTypes,
		DependencyIndexes: file_order_service_proto_order_proto_depIdxs,
		MessageInfos:      file_order_service_proto_order_proto_msgTypes,
	}.Build()
	File_order_service_proto_order_proto = out.File
	file_order_service_proto_order_proto_goTypes = nil
	file_order_service_proto_order_proto_depIdxs = nil
}
